resolver 127.0.0.11 valid=10s ipv6=off;

server {
    listen 80;
    server_name driveeup.ru www.driveeup.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /api/ {
        set $upstream_backend backend;
        proxy_pass http://$upstream_backend:8000$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        set $upstream_frontend frontend;
        proxy_pass http://$upstream_frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_intercept_errors on;
        error_page 404 = @spa_fallback;
    }

    location @spa_fallback {
        rewrite ^ /index.html break;
        set $upstream_frontend_spa frontend;
        proxy_pass http://$upstream_frontend_spa:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
